### ISSUE TITLE
runtime/cgo: pthread_create failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by Drjacky** [xm1k3/cent#70]
```bash
➜  cent git:(main) cent validate
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x18941a0dc m=2 sigcode=0

goroutine 0 [idle]:
runtime: g 0: unknown pc 0x18941a0dc
stack: frame={sp:0x16d732c00, fp:0x0} stack=[0x16cf37328,0x16d732f28)
0x000000016d732b00:  0x0000000000000000  0x0000000100000008
0x000000016d732b10:  0x0000000102edef94 <runtime.(*mcache).nextFree+0x0000000000000084>  0x0000000000000000
0x000000016d732b20:  0x0000000032aaaba2  0x0000000000000000
0x000000016d732b30:  0x0000000000000000  0x0000000000000000
0x000000016d732b40:  0x0000000000000000  0x0000000000000000
0x000000016d732b50:  0x0000000000000000  0x0000000000000000
0x000000016d732b60:  0x0000000000000007  0x0000000000000000
0x000000016d732b70:  0x0000000000000000  0x0000000000000000
0x000000016d732b80:  0x0000000000000000  0x0000000000000000
0x000000016d732b90:  0x0000000000000000  0x0000000000000000
0x000000016d732ba0:  0x0000000000000000  0x0000000000000000
0x000000016d732bb0:  0x0000000000000000  0x0000000000000000
0x000000016d732bc0:  0x0000000000000000  0x0000000000000000
0x000000016d732bd0:  0x0000000000000000  0x0000000000000000
0x000000016d732be0:  0x000000000000003c  0x00000001dfc38508
0x000000016d732bf0:  0x000000016d732c10  0x8a338001892f6970
0x000000016d732c00: <0x0000000000000000  0x0000000000000003
0x000000016d732c10:  0x000000016d732c48  0x000000016d733000
0x000000016d732c20:  0x000000016d732c60  0xe10d80018935da40
0x000000016d732c30:  0x00000000007ff000  0xffffffffdfc38508
0x000000016d732c40:  0x0000000000000000  0x00000000fffff9df
0x000000016d732c50:  0x00000000007ff000  0x00000001dfc38508
0x000000016d732c60:  0x000000016d732c90  0x5544000102ed11c4
0x000000016d732c70:  0x00000001893621fd  0x0000000000000003
0x000000016d732c80:  0x00000000007ff000  0x0000000000000023
0x000000016d732c90:  0x000000016d732d00  0x0000000102ed110c <threadentry+0x0000000000000000>
0x000000016d732ca0:  0x0000000000000000  0xffffffff00000000
0x000000016d732cb0:  0x0000000054484441  0x0000000000000000
0x000000016d732cc0:  0x0000000000000000  0x0000000000800000
0x000000016d732cd0:  0x00000000000008ff  0x0000000010010101
0x000000016d732ce0:  0x0000000000000000  0x0000000000000000
0x000000016d732cf0:  0x000000016d732900  0x000000016d732ca8
runtime: g 0: unknown pc 0x18941a0dc
stack: frame={sp:0x16d732c00, fp:0x0} stack=[0x16cf37328,0x16d732f28)
0x000000016d732b00:  0x0000000000000000  0x0000000100000008
0x000000016d732b10:  0x0000000102edef94 <runtime.(*mcache).nextFree+0x0000000000000084>  0x0000000000000000
0x000000016d732b20:  0x0000000032aaaba2  0x0000000000000000
0x000000016d732b30:  0x0000000000000000  0x0000000000000000
0x000000016d732b40:  0x0000000000000000  0x0000000000000000
0x000000016d732b50:  0x0000000000000000  0x0000000000000000
0x000000016d732b60:  0x0000000000000007  0x0000000000000000
0x000000016d732b70:  0x0000000000000000  0x0000000000000000
0x000000016d732b80:  0x0000000000000000  0x0000000000000000
0x000000016d732b90:  0x0000000000000000  0x0000000000000000
0x000000016d732ba0:  0x0000000000000000  0x0000000000000000
0x000000016d732bb0:  0x0000000000000000  0x0000000000000000
0x000000016d732bc0:  0x0000000000000000  0x0000000000000000
0x000000016d732bd0:  0x0000000000000000  0x0000000000000000
0x000000016d732be0:  0x000000000000003c  0x00000001dfc38508
0x000000016d732bf0:  0x000000016d732c10  0x8a338001892f6970
0x000000016d732c00: <0x0000000000000000  0x0000000000000003
0x000000016d732c10:  0x000000016d732c48  0x000000016d733000
0x000000016d732c20:  0x000000016d732c60  0xe10d80018935da40
0x000000016d732c30:  0x00000000007ff000  0xffffffffdfc38508
0x000000016d732c40:  0x0000000000000000  0x00000000fffff9df
0x000000016d732c50:  0x00000000007ff000  0x00000001dfc38508
0x000000016d732c60:  0x000000016d732c90  0x5544000102ed11c4
0x000000016d732c70:  0x00000001893621fd  0x0000000000000003
0x000000016d732c80:  0x00000000007ff000  0x0000000000000023
0x000000016d732c90:  0x000000016d732d00  0x0000000102ed110c <threadentry+0x0000000000000000>
0x000000016d732ca0:  0x0000000000000000  0xffffffff00000000
0x000000016d732cb0:  0x0000000054484441  0x0000000000000000
0x000000016d732cc0:  0x0000000000000000  0x0000000000800000
0x000000016d732cd0:  0x00000000000008ff  0x0000000010010101
0x000000016d732ce0:  0x0000000000000000  0x0000000000000000
0x000000016d732cf0:  0x000000016d732900  0x000000016d732ca8

goroutine 1 [runnable]:
syscall.syscall(0x1404365e960?, 0x2e?, 0x14000529af8?, 0x102fb195c?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/sys_darwin.go:23 +0x58 fp=0x14000529ab0 sp=0x14000529a20 pc=0x102f37868
syscall.Lstat({0x1404365e960?, 0x0?}, 0x140436601d8)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/syscall/zsyscall_darwin_arm64.go:1943 +0x70 fp=0x14000529b00 sp=0x14000529ab0 pc=0x102f88550
os.lstatNolog.func1(...)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/os/stat_unix.go:45
os.ignoringEINTR(...)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/os/file_posix.go:251
os.lstatNolog({0x1404365e960, 0x2e})
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/os/stat_unix.go:44 +0x50 fp=0x14000529b40 sp=0x14000529b00 pc=0x102fb1980
os.Lstat({0x1404365e960, 0x2e})
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/os/stat.go:22 +0x30 fp=0x14000529b60 sp=0x14000529b40 pc=0x102fb13a0
path/filepath.walk({0x103441269, 0x15}, {0x10367b9a8, 0x140002fcdd0}, 0x14000529cb8)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/path/filepath/path.go:495 +0x148 fp=0x14000529c30 sp=0x14000529b60 pc=0x1030597b8
path/filepath.Walk({0x103441269, 0x15}, 0x1400029fcb8)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/path/filepath/path.go:572 +0x6c fp=0x14000529c80 sp=0x14000529c30 pc=0x103059c5c
github.com/xm1k3/cent/cmd.glob..func6(0x14000208c00?, {0x103438036?, 0x4?, 0x103438016?})
	/Users/usernameee/go/pkg/mod/github.com/xm1k3/cent@v1.3.3/cmd/validate.go:29 +0x68 fp=0x14000529cd0 sp=0x14000529c80 pc=0x103436e08
github.com/spf13/cobra.(*Command).execute(0x103a88220, {0x103ac3a60, 0x0, 0x0})
	/Users/usernameee/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x654 fp=0x14000529e10 sp=0x14000529cd0 pc=0x10306e2f4
github.com/spf13/cobra.(*Command).ExecuteC(0x103a87980)
	/Users/usernameee/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320 fp=0x14000529ed0 sp=0x14000529e10 pc=0x10306ea30
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/usernameee/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/xm1k3/cent/cmd.Execute()
	/Users/usernameee/go/pkg/mod/github.com/xm1k3/cent@v1.3.3/cmd/root.go:86 +0x24 fp=0x14000529f20 sp=0x14000529ed0 pc=0x103435ac4
main.main()
	/Users/usernameee/go/pkg/mod/github.com/xm1k3/cent@v1.3.3/main.go:21 +0x1c fp=0x14000529f30 sp=0x14000529f20 pc=0x10343748c
runtime.main()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:267 +0x2bc fp=0x14000529fd0 sp=0x14000529f30 pc=0x102f0a80c
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000529fd0 sp=0x14000529fd0 pc=0x102f3b084

goroutine 2 [force gc (idle), 1 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000070f90 sp=0x14000070f70 pc=0x102f0ac38
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:404
runtime.forcegchelper()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:322 +0xb8 fp=0x14000070fd0 sp=0x14000070f90 pc=0x102f0aac8
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000070fd0 sp=0x14000070fd0 pc=0x102f3b084
created by runtime.init.6 in goroutine 1
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:310 +0x24

goroutine 3 [runnable]:
runtime.goschedIfBusy()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:361 +0x34 fp=0x14000071760 sp=0x14000071740 pc=0x102f0ab54
runtime.bgsweep(0x0?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgcsweep.go:305 +0x18c fp=0x140000717b0 sp=0x14000071760 pc=0x102ef76ac
runtime.gcenable.func1()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:200 +0x28 fp=0x140000717d0 sp=0x140000717b0 pc=0x102eec0b8
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140000717d0 sp=0x140000717d0 pc=0x102f3b084
created by runtime.gcenable in goroutine 1
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:200 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x140000480e0?, 0x10352f350?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000071f50 sp=0x14000071f30 pc=0x102f0ac38
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x103a8e720)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgcscavenge.go:425 +0x5c fp=0x14000071f80 sp=0x14000071f50 pc=0x102ef4e6c
runtime.bgscavenge(0x0?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgcscavenge.go:658 +0xac fp=0x14000071fb0 sp=0x14000071f80 pc=0x102ef542c
runtime.gcenable.func2()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:201 +0x28 fp=0x14000071fd0 sp=0x14000071fb0 pc=0x102eec058
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000071fd0 sp=0x14000071fd0 pc=0x102f3b084
created by runtime.gcenable in goroutine 1
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:201 +0xac

goroutine 5 [finalizer wait, 1 minutes]:
runtime.gopark(0x140000705a8?, 0x102f363f4?, 0x1?, 0x5?, 0x102f561f4?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000070580 sp=0x14000070560 pc=0x102f0ac38
runtime.runfinq()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mfinal.go:193 +0x108 fp=0x140000707d0 sp=0x14000070580 pc=0x102eeb168
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140000707d0 sp=0x140000707d0 pc=0x102f3b084
created by runtime.createfing in goroutine 1
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mfinal.go:163 +0x80

goroutine 6 [GC worker (idle), 1 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000072730 sp=0x14000072710 pc=0x102f0ac38
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1295 +0xd8 fp=0x140000727d0 sp=0x14000072730 pc=0x102eedd18
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140000727d0 sp=0x140000727d0 pc=0x102f3b084
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1219 +0x28

goroutine 18 [GC worker (idle), 1 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:398 +0xc8 fp=0x1400006c730 sp=0x1400006c710 pc=0x102f0ac38
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1295 +0xd8 fp=0x1400006c7d0 sp=0x1400006c730 pc=0x102eedd18
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400006c7d0 sp=0x1400006c7d0 pc=0x102f3b084
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1219 +0x28

goroutine 34 [GC worker (idle), 1 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:398 +0xc8 fp=0x1400050e730 sp=0x1400050e710 pc=0x102f0ac38
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1295 +0xd8 fp=0x1400050e7d0 sp=0x1400050e730 pc=0x102eedd18
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400050e7d0 sp=0x1400050e7d0 pc=0x102f3b084
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1219 +0x28

goroutine 19 [GC worker (idle), 1 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:398 +0xc8 fp=0x1400006cf30 sp=0x1400006cf10 pc=0x102f0ac38
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1295 +0xd8 fp=0x1400006cfd0 sp=0x1400006cf30 pc=0x102eedd18
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400006cfd0 sp=0x1400006cfd0 pc=0x102f3b084
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1219 +0x28

goroutine 20 [GC worker (idle), 1 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:398 +0xc8 fp=0x1400006d730 sp=0x1400006d710 pc=0x102f0ac38
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1295 +0xd8 fp=0x1400006d7d0 sp=0x1400006d730 pc=0x102eedd18
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400006d7d0 sp=0x1400006d7d0 pc=0x102f3b084
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1219 +0x28

goroutine 35 [GC worker (idle), 1 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:398 +0xc8 fp=0x1400050ef30 sp=0x1400050ef10 pc=0x102f0ac38
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1295 +0xd8 fp=0x1400050efd0 sp=0x1400050ef30 pc=0x102eedd18
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400050efd0 sp=0x1400050efd0 pc=0x102f3b084
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1219 +0x28

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x77e630a9750?, 0x1?, 0x5e?, 0x90?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:398 +0xc8 fp=0x1400006df30 sp=0x1400006df10 pc=0x102f0ac38
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1295 +0xd8 fp=0x1400006dfd0 sp=0x1400006df30 pc=0x102eedd18
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400006dfd0 sp=0x1400006dfd0 pc=0x102f3b084
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1219 +0x28

goroutine 36 [GC worker (idle), 1 minutes]:
runtime.gopark(0x778bd2f2a1e?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:398 +0xc8 fp=0x1400050f730 sp=0x1400050f710 pc=0x102f0ac38
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1295 +0xd8 fp=0x1400050f7d0 sp=0x1400050f730 pc=0x102eedd18
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400050f7d0 sp=0x1400050f7d0 pc=0x102f3b084
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1219 +0x28

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x103ac4ca0?, 0x1?, 0xa5?, 0xf?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:398 +0xc8 fp=0x1400050ff30 sp=0x1400050ff10 pc=0x102f0ac38
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1295 +0xd8 fp=0x1400050ffd0 sp=0x1400050ff30 pc=0x102eedd18
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400050ffd0 sp=0x1400050ffd0 pc=0x102f3b084
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1219 +0x28

goroutine 22 [GC worker (idle), 1 minutes]:
runtime.gopark(0x778c33daa2d?, 0x1?, 0xe6?, 0x2d?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:398 +0xc8 fp=0x1400006e730 sp=0x1400006e710 pc=0x102f0ac38
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/mgc.go:1295 +0xd8 fp=0x1400006e7d0 sp=0x1400006e730 pc=0x102eedd18
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400006e7d0 sp=0x1400006e7d0 pc=0x102f3b084
created by runtime.gcBgMarkStartWorkers in goroutine 1
.
.
.

```

**Comment by simonlee-hello** [comment]
same as your question. runtime/cgo: pthread_create failed: Resource temporarily unavailable

**Comment by yangyang-zhang** [comment]
same as your question2. runtime/cgo: pthread_create failed: Resource temporarily unavailable， My computer is an Apple Mac M1 Pro
